import { Router } from "express";
import authRoutes from "./authRoutes";
import analyticsRoutes from "./analyticsRoutes";
import storeRoutes from "./storeRoutes";
import roleRoutes from "./roleRoutes";
import userRoutes from "./userRoutes";
import categoryRoutes from "./categoryRoutes";
import productRoutes from "./productRoutes";
import productItemRoutes from "./productItemRoutes";
import customerRoutes from "./customerRoutes";
import bookingRoutes from "./bookingRoutes";
import offerRoutes from "./offerRoutes";
import bookingItemRoutes from "./bookingItemRoutes";
import paymentModeRoutes from "./paymentModeRoutes";
import storeBankAccountRoutes from "./storeBankAccountRoutes";
import transactionCategoryRoutes from "./transactionCategoryRoutes";
import transactionRoutes from "./transactionRoutes";
import vendorTypeRoutes from "./vendorTypeRoutes";
import vendorRoutes from "./vendorRoutes";
import serviceTypeRoutes from "./serviceTypeRoutes";
import itemServiceLogRoutes from "./itemServiceLogRoutes";
import timeSlotRoutes from "./timeSlotRoutes";
import accessoryRoutes from "./accessoryRoutes";
import attendanceRoutes from "./attendanceRoutes";
import holidayRoutes from "./holidayRoutes";
import staffLeaveRoutes from "./staffLeaveRoutes";
import staffSalaryRoutes from "./staffSalaryRoutes";
import staffAdvanceRoutes from "./staffAdvanceRoutes";
import reminderRoutes from "./reminderRoutes";
import creditVoucherRoutes from "./creditVoucherRoutes";
import auditLogRoutes from "./auditLogRoutes";
import purchaseInvoiceRoutes from "./purchaseInvoiceRoutes";
import purchaseItemRoutes from "./purchaseItemRoutes";
import retailSaleRoutes from "./retailSaleRoutes";
import retailSaleItemRoutes from "./retailSaleItemRoutes";
import subscriptionPlanRoutes from "./subscriptionPlanRoutes";
import storeSubscriptionRoutes from "./storeSubscriptionRoutes";

const router = Router();
router.use("/auth", authRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/stores", storeRoutes);
router.use("/roles", roleRoutes);
router.use("/users", userRoutes);
router.use("/categorys", categoryRoutes);
router.use("/products", productRoutes);
router.use("/productItems", productItemRoutes);
router.use("/customers", customerRoutes);
router.use("/bookings", bookingRoutes);
router.use("/offers", offerRoutes);
router.use("/bookingItems", bookingItemRoutes);
router.use("/paymentModes", paymentModeRoutes);
router.use("/storeBankAccounts", storeBankAccountRoutes);
router.use("/transactionCategorys", transactionCategoryRoutes);
router.use("/transactions", transactionRoutes);
router.use("/vendorTypes", vendorTypeRoutes);
router.use("/vendors", vendorRoutes);
router.use("/serviceTypes", serviceTypeRoutes);
router.use("/itemServiceLogs", itemServiceLogRoutes);
router.use("/timeSlots", timeSlotRoutes);
router.use("/accessorys", accessoryRoutes);
router.use("/attendances", attendanceRoutes);
router.use("/holidays", holidayRoutes);
router.use("/staffLeaves", staffLeaveRoutes);
router.use("/staffSalarys", staffSalaryRoutes);
router.use("/staffAdvances", staffAdvanceRoutes);
router.use("/reminders", reminderRoutes);
router.use("/creditVouchers", creditVoucherRoutes);
router.use("/auditLogs", auditLogRoutes);
router.use("/purchaseInvoices", purchaseInvoiceRoutes);
router.use("/purchaseItems", purchaseItemRoutes);
router.use("/retailSales", retailSaleRoutes);
router.use("/retailSaleItems", retailSaleItemRoutes);
router.use("/subscriptionPlans", subscriptionPlanRoutes);
router.use("/storeSubscriptions", storeSubscriptionRoutes);
export default router;
